#!/bin/bash
#
# tomcat startup script for the Tomcat server
#
# chkconfig: 345 80 20
# description: start the tomcat deamon
#
# Source function library
. /etc/rc.d/init.d/functions
export  PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/java/default/bin:$PATH 

prog=tomcat
JAVA_HOME=/usr/java/default
export JAVA_HOME
CATALANA_HOME=/opt/tomcat
export CATALINA_HOME

check_prog() {
	local prog=$1
	result=`ps aux |awk '/'"$prog"'/ && !/awk/'`
	[[ $result ]] && return 0 || return 1
}

killer() {
	local prog=$1
	pid=`ps aux | awk '/'"$prog"'/ && !/awk/ {print $2}'`
	[[ $pid ]] && kill $pid
}

case "$1" in
start)
	echo "Starting Tomcat..."
	if ! check_prog "tomcat-juli.jar" ;then
		daemon --user tomcat /opt/tomcat/bin/catalina.sh start 
	else
		killer "tomcat-juli.jar" && sleep 2	
		daemon --user tomcat /opt/tomcat/bin/catalina.sh start
	fi
;;

stop)
	echo "Stopping Tomcat..."
	killer 'tomcat-juli.jar'
;;

restart)
	echo "Stopping Tomcat..."
	killer 'tomcat-juli.jar' && sleep 2
	echo "Starting Tomcat..."
	daemon --user tomcat /opt/tomcat/bin/catalina.sh start
;;

status)
	if check_prog 'tomcat-juli.jar';then
		echo 'tomcat is running...'
	else
		echo 'tomcat not run.'
	fi
;;

*)
	echo "Usage: $prog {start|stop|restart|status}" ;;
esac
exit 0

